name: "flutter_locales"
description: "Easily localize your app to multiple languages"
version: "2.0.2"
homepage: "https://popal.dev"
repository: "https://github.com/ajmalajmalvp/flutter_locals_package"
documentation: "https://github.com/ajmalajmalvp/flutter_locals_package"
issue_tracker: "https://github.com/ajmalajmalvp/flutter_locals_package/issues"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
